FROM node:20-slim

# # Instalar dependencias necesarias
RUN apt-get update && apt-get install -y \
  curl \
  git 

WORKDIR /workspaces

# # Exponer puerto (Backend)
# EXPOSE 3000

# # Exponer el puerto (Frontend)
# EXPOSE 5173